using Dapper;
using Microsoft.Extensions.Logging;
using NDK.Core.Attributes;
using NDK.Core.Models;
using NDK.Core.Utility;
using NDK.Database.ExtensionMethods;
using NDK.Database.ExtensionMethods.Internal;
using NDK.Database.Handlers;
using NDK.Database.Interfaces;
using NDK.Database.Models;
using System.Data.Common;
using System.Reflection;
using System.Text;

namespace NDK.Database.Base
{
    public class NdkSimpleEntityRepository<T, TUser> : NdkBaseRepository, INdkRepository<T> where T : NdkBaseModel where TUser:NdkUser
    {
        private readonly TUser _loggedUser;
        private readonly NdkDbConnectionHandler _connectionHandler;
        private readonly NdkSimpleEntityRepositoryConfig _config;
        private readonly ILogger _logger;

        public NdkSimpleEntityRepository(TUser loggedUser,
                                         NdkDbConnectionHandler connectionHandler, 
                                         NdkSimpleEntityRepositoryConfig config, 
                                         ILogger<NdkSimpleEntityRepository<T,TUser>> logger)
        {
            _loggedUser = loggedUser;
            _connectionHandler = connectionHandler;
            _config = config;
            _logger = logger;
        }

        public virtual NdkResponse<long> Delete(T entity, DbConnection connection)
        {
            NdkResponse<long> response = new();

            base.ApplyBaseModelValues(_loggedUser, entity);

            try
            {
                var result = connection.ExecuteScalar<object>(GetDeleteString(entity), entity);

                response.Result = Convert.ToInt64(result);
            }
            catch (Exception ex)
            {
                base.HandleException(ex, response, _logger);
            }

            return response;
        }

        public virtual NdkListResponse<T> GetByRequest(NdkRequest request, DbConnection connection)
        {
            NdkListResponse<T> response = new();

            T entity = Activator.CreateInstance<T>();
            var queryParams = request.GetRequestData(GetSelectString(entity), this._connectionHandler._configuration);

            response.Result = connection.Query<T>(queryParams.query, queryParams).ToList();

            var countRequest = request.Clone();
            countRequest.Paging = null;

            queryParams = request.GetRequestData(GetSelectCountString(entity), this._connectionHandler._configuration);

            response.AvailableItems = connection.Query<long>(queryParams.query, queryParams).ToList().FirstOrDefault();


            return response;
        }

        public virtual NdkResponse<long> Insert(T entity, DbConnection connection)
        {
            NdkResponse<long> response = new();

            base.ApplyBaseModelValues(_loggedUser, entity);

            try
            {
                var result = connection.ExecuteScalar<object>(GetInsertSql(entity), entity);

                response.Result = Convert.ToInt64(result);
            }
            catch(Exception ex)
            {
                base.HandleException(ex, response, _logger);
            }
            

            return response;
        }

        public virtual NdkResponse<long> Update(T entity, DbConnection connection)
        {
            NdkResponse<long> response = new();

            base.ApplyBaseModelValues(_loggedUser, entity);

            try
            {
                var result = connection.ExecuteScalar<object>(GetUpdateSql(entity), entity);

                response.Result = Convert.ToInt64(result);
            }
            catch (Exception ex)
            {
                base.HandleException(ex, response, _logger);
            }

            return response;
        }

        private string GetInsertSql(T entity)
        {
            StringBuilder sb = new StringBuilder();

            ValidateInput(entity);

            IEnumerable<PropertyInfo> properties = entity.GetType().GetProperties().Where(x => !x.GetCustomAttribute<NdkPrimaryKey>()?.AutoGenerated ?? false);

            sb.AppendLine($"INSERT INTO {_config.GetEntityTable(entity.GetType())} ");

            sb.AppendLine($"({string.Join(',', properties.Select(x => x.Name))})");
            sb.AppendLine($"VALUES({string.Join(',', properties.Select(x => $"{_connectionHandler._configuration.GetParamSymbol()}{x.Name}"))}) ");

            sb.AppendLine(_connectionHandler._configuration.GetInsertSelectResult());

            return sb.ToString();
        }

        private string GetUpdateSql(T entity)
        {
            StringBuilder sb = new StringBuilder();

            ValidateInput(entity);

            IEnumerable<PropertyInfo> properties = entity.GetType().GetProperties().Where(x => !x.GetCustomAttribute<NdkPrimaryKey>()?.AutoGenerated ?? false);

            sb.AppendLine($"UPDATE {_config.GetEntityTable(entity.GetType())} SET");
            sb.AppendLine($"{string.Join(',', properties.Select(x => $"{x.Name} = {_connectionHandler._configuration.GetParamSymbol()}{x.Name}"))}");
            sb.AppendLine($"WHERE Id = {_connectionHandler._configuration.GetParamSymbol()}Id");
            sb.AppendLine(_connectionHandler._configuration.GetUpdateOrDeleteResult());


            return sb.ToString();
        }

        private string GetDeleteString(T entity)
        {
            StringBuilder sb = new StringBuilder();

            ValidateInput(entity);

            IEnumerable<PropertyInfo> properties = entity.GetType().GetProperties().Where(x => !x.GetCustomAttribute<NdkPrimaryKey>()?.AutoGenerated ?? false);

            sb.AppendLine($"DELETE FROM {_config.GetEntityTable(entity.GetType())} WHERE ID = {_connectionHandler._configuration.GetParamSymbol()}Id ");
            sb.AppendLine(_connectionHandler._configuration.GetUpdateOrDeleteResult());



            return sb.ToString();
        }

        private string GetSelectString(T entity)
        {
            StringBuilder sb = new StringBuilder();

            ValidateInput(entity);

            IEnumerable<PropertyInfo> properties = entity.GetType().GetProperties();

            sb.AppendLine($"SELECT {string.Join(",", properties.Select(x => x.Name))} FROM {_config.GetEntityTable(entity.GetType())} ");

            return sb.ToString();
        }

        private string GetSelectCountString(T entity)
        {
            StringBuilder sb = new StringBuilder();

            ValidateInput(entity);

            IEnumerable<PropertyInfo> properties = entity.GetType().GetProperties();

            sb.AppendLine($"SELECT COUNT(Id) FROM {_config.GetEntityTable(entity.GetType())} ");

            return sb.ToString();
        }

        private void ValidateInput(T entity)
        {
            var props = entity.GetType().GetProperties();

            if (!props.AsList().Exists(x => x.GetCustomAttribute<NdkPrimaryKey>() != null))
            {
                throw new InvalidDataException("Should provide the NdkPrimaryKey attribute to the Model you're trying to use with this method");
            }
        }
    }


}
