
name: Publish NuGet Package to Local Folder

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x' # Update to the desired version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Pack the project
        run: dotnet pack --configuration Release --output ./nuget-packages

      - name: Publish packages
        run: dotnet nuget push ./nuget-packages/*.nupkg --source https://api.nuget.org/v3/index.json --api-key oy2kkj6fzbef7tju3tnqj27topbdjtlufkqwn6riuyeg6m
